<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload303922ad6a25fedb016bdec114d170d6($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'presshub\\client' => '/src/Presshub/Presshub.php',
            'presshub\\template' => '/src/Presshub/Template.php',
            'presshub\\template\\base' => '/src/Presshub/Template/Base.php',
            'presshub\\template\\component' => '/src/Presshub/Template/Component.php',
            'presshub\\template\\componentbase' => '/src/Presshub/Template/ComponentBase.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload303922ad6a25fedb016bdec114d170d6', true);
// @codeCoverageIgnoreEnd
